name: worldchat
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  get: ^4.7.2
  firebase_storage: ^12.4.6
  cloud_firestore: ^5.6.8
  flutter_plugin_android_lifecycle: ^2.0.19
  flutter_svg: ^2.1.0
  google_sign_in: ^7.0.0
  video_player: ^2.10.0
  video_compress: ^3.1.4
  flutter_facebook_auth: ^7.1.2
  firebase_auth: ^5.6.0
  firebase_core: ^3.8.0
  file_picker: ^10.2.0
  record: ^6.0.0
  audioplayers: ^6.5.0
  path_provider: ^2.1.1
  intl: ^0.20.2
  provider: ^6.1.1
  youtube_explode_dart: ^2.4.2
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.6.15
  flutter_dotenv: ^5.1.0
  flutter_tts: ^3.6.3
  html: ^0.15.0
  speech_to_text: ^7.0.0
  image: ^4.5.4
  pdf: ^3.10.0
  pdfx: ^2.0.1
  open_file: ^3.3.3
  translator: ^1.0.3+1
  http: ^1.1.0
  cloudinary_flutter: ^1.3.0
  http_parser: ^4.0.2
  crypto: ^3.0.3
  cached_network_image: ^3.2.3






 # shared_preferences: ^2.2.2  # Save user's language preference
  easy_localization: ^3.0.2   # Alternative to 'get' for more complex apps
  dio: ^5.3.3                # If fetching translations from a server













 # cached_network_image: ^3.3.0
  photo_view: ^0.14.0
  flutter_pdfview: ^1.3.1
  #path_provider: ^2.1.1
  #http: ^0.13.5
 # permission_handler: ^10.4.0
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2  # For current location functionality
##  permission_handler: ^10.4.4  # or the latest version
  permission_handler:
    git:
      url: https://github.com/sharifji/flutter-permission-handler.git
      path: permission_handler  # Add this line
      ref: main  # Explicitly use the main branch

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true